### ISSUE TITLE
error while trying to send a message

### ISSUE THREAD

**Issue by Mounthazeer** [Neurotech-HQ/heyoo#10]
i am getting this error while trying to send a message

Invalid recipient for test number

**Comment by Kalebu** [comment]
Hi @Mounthazeer 

It seems like you haven't verified your test number in a Facebook developer portal 

Before you go to production, all recipients must be verified, Please cross check

**Comment by Mounthazeer** [comment]
do you mean the receivers number ?
i added one and now i can send using the curl command in step 2

however getting this problem now it is showing me the following but no message is sent
![done](https://user-images.githubusercontent.com/58270012/170861771-8aa2320d-8ad2-4d12-8d17-a157525718d0.PNG)

**Comment by Kalebu** [comment]
I have noticed some patterns like to able to send messages that are not **pre-approved template*, you will need to set up your [webhook](https://github.com/Neurotech-HQ/heyoo/blob/main/hook.py) first.

_Originally posted by @Kalebu in https://github.com/Neurotech-HQ/heyoo/issues/3#issuecomment-1133880881_

**Comment by Mounthazeer** [comment]
so i have to setup the webhook 
i am having some trouble though

i dont understand the following steps:
From Heroku settings configure your Environment varibles of your WhatsAapp application.
Setup and verify your webhook url and token then subscribe to messages.

**Comment by Mounthazeer** [comment]
hi i have been trying to set up the webhook however
when i run my url in a browser as stated here https://github.com/JAXPARROW/whatsapi-flask-webhook
i get this:
Invalid verification token

**Comment by Kalebu** [comment]
please make sure you specify the same verification token while configuring you're webhook on the developer portal

**Comment by Mounthazeer** [comment]
the token i specify in heroku right but still having problems though
![image](https://user-images.githubusercontent.com/58270012/170908254-78e17a63-6355-43c6-a6de-423ece38d586.png)

**Comment by Mounthazeer** [comment]
if i paste the url in a browser it outputs 'hello it works' however if i put /whatsapi at the end it says invalid verification token

**Comment by Kalebu** [comment]
Hello @Mounthazeer 

Please make sure to set up your environment variables to reflect your credentials in case you have used [Deploy heroku](https://heroku.com/deploy?template=https://github.com/JAXPARROW/whatsapi-flask-webhook) to deploy your webook. 

Let me know if you still have issues
