### ISSUE TITLE
Not able to send text messages

### ISSUE THREAD

**Issue by iqbalcrat** [Neurotech-HQ/heyoo#11]
While sending text messages without any template, getting 200 response but message is not being received by the target phone phone.

**Comment by joao-voltarelli** [comment]
@iqbalcrat 
Try replying to the template message sent to the target phone and after that try again sending just a text message, this worked for me. 

Apparently it is only possible to send messages other than templates after the target phone responds to an initial message.

Reference: https://developers.facebook.com/community/threads/425605939396247/
