### ISSUE TITLE
Not able to send messages to some numbers

### ISSUE THREAD

**Issue by Aman8T** [Neurotech-HQ/heyoo#12]
While using the code in python, a few numbers were able to receive the message and images, but others did not. The message is sent , but is not received, how to sole this??

**Comment by Kalebu** [comment]
Hi @Aman8T 

I think this has nothing to do with the wrapper but is more of an issue with the [WhatsApp Cloud API](https://developers.facebook.com/docs/whatsapp/cloud-api)

**Comment by Aman8T** [comment]
Hi, I was able to solve the problem and create a bot that can send and receive messages, thanks to this beautiful package of yours. I am just stuck on, how do we receive the location?? i am able to send a location using latitude and longitude, but how to receive it.

**Comment by Kalebu** [comment]
Hi @Aman8T 

I have updated the documentation, including how to receive a location, please have a look 

https://github.com/Neurotech-HQ/heyoo#webhook
