### ISSUE TITLE
Send reply button only displays three reply buttons.

### ISSUE THREAD

**Issue by ahmadhadidi** [Neurotech-HQ/heyoo#17]
Hello,

I've been using the library for a while and I would like to communicate this information to anyone who's going to use it (Perhaps this could be included in the documentation of the functions):

The function "send_reply_button" should say that it only shows 3 reply buttons. If more are posted then no reply buttons will appear.

```
"""
        Send a message with a maximum of three reply buttons beneath it.
        :param button: Button object, check https://github.com/Neurotech-HQ/heyoo#sending-interactive-reply-buttons
        for an example.
        :param recipient_id: Typically the phone number of the recipient
        :return:
"""
```

**Comment by Kalebu** [comment]
Hi @ahmadhadidi  Thanks for mentioning this, You can also send a pull request to modify the documentation and methods docstrings and I will merge it right away

**Comment by Kalebu** [comment]
Thank you @ahmadhadidi  for your awesome contribution 

I have updated the docstring accordingly, I will now close this issue
