### ISSUE TITLE
Send_button text may not exceed 20 characters

### ISSUE THREAD

**Issue by ahmadhadidi** [Neurotech-HQ/heyoo#18]
Hello again,

I would like to propose in the API documentation that we warn the dev that they cannot exceed 20 characters for each button name and row title.

```
"""
    Send an interactive message with buttons.

    :param button: Button object, rows-title may not exceed 20 characters
    check https://github.com/Neurotech-HQ/heyoo#sending-interactive-reply-buttons for an example.
    :param recipient_id:  Typically the phone number of the recepient
    :return:
"""
```

**Comment by Kalebu** [comment]
Thank you @ahmadhadidi  for your contributions, I have updated the docstring for the methods accordingly 

I will now close this issue
