### ISSUE TITLE
save input from the users and send another message

### ISSUE THREAD

**Issue by nir-flow** [Neurotech-HQ/heyoo#20]
First of all I must say that the project is amazing!!
I need to send a message, then save the input that comes from the user, then send another message and again save the input. How can I do this?

**Comment by jay-patel-cognoai** [comment]
hi @Kalebu , I also wondered how can we log API request or in general if I am calling an API through a library then what is a general practise , How can we log API request response.... like sqlalchemy with sqlite3 ?

**Comment by Kalebu** [comment]
Hi @jay-patel-cognoai, Are you talking about logging the hook response or heyoo methods response ?

If its hook, It already included in the **hook** on how to log it 

```    # Handle Webhook Subscriptions
    data = request.get_json()
    logging.info("Received webhook data: %s", data)
```

But if you're talking about specific **heyoo** message like ```send_message```, they do return a json response by default so you can easily log the response like this;

```python
>>> r = messenger.send_message('hi there', '34xxxx')
>>> print(r)
````
You can then save the log whenever you want whether to log file, text file, or database or Are you also suggesting we should include API Response logging by default to the library right ?

**Comment by jay-patel-cognoai** [comment]
Just wanted to know do libraries ever use any kind of database for their internal functioning.

**Comment by Kalebu** [comment]
Well it depends on the design choices of a particular library, For **heyoo** we don't 

I will mark this issue #20  as resolved
