### ISSUE TITLE
Requests Package Missing 

### ISSUE THREAD

**Issue by seun-beta** [Neurotech-HQ/heyoo#3]
Heyoo package requires `requests`. But the package is missing.

`import requests
ModuleNotFoundError: No module named 'requests'`

I am also available to raise PR's to fix the issues

**Comment by Kalebu** [comment]
I guess I forgot to include requests in the required setup.py

Thank you for pointing out this 

Looking forward to seeing your pull requests

**Comment by seun-beta** [comment]
No problem. I am also trying out all the features. 

I haven't been able to receive any message yet both using heyoo and Whatsapp Cloud API. 

I don't know if I am missing anything

**Comment by Kalebu** [comment]
To see if you're good try to send a simple template message like below and let me know if it works 

```python
>>> from heyoo import WhatsApp
>>> messenger = WhatsApp('TOKEN',  phone_number_id='104xxxxxx')
>>> messenger.send_template('hello_world', 'your number')
```

**Comment by Kalebu** [comment]
> Heyoo package requires `requests`. But the package is missing.
> 
> `import requests ModuleNotFoundError: No module named 'requests'`
> 
> I am also available to raise PR's to fix the issues

I have already updated this, changes will be included in the next version of the package
