### ISSUE TITLE
requests_toolbelt is not listed as a dependency

### ISSUE THREAD

**Issue by soerenetler** [Neurotech-HQ/heyoo#31]
Hi,
`requests_toolbelt` is used by not probably defined as a dependency in the `setup.py`. It is just used in one place.
I think it would be a better approach to remove it to not add too many dependencies. I don't think it is even necessary there.

I would happily create a PR if it is decided which approach (add a dependency or change code) to go with.

**Comment by Kalebu** [comment]
Hi @soerenetler 

This makes sense, if you have a better approach to reproduce what requests_toolbelt does without any extra dependencies please proceed and `Create a PR for it`.

**Comment by soerenetler** [comment]
This is solved with #36
