### ISSUE TITLE
Only useable with Python 3.10

### ISSUE THREAD

**Issue by soerenetler** [Neurotech-HQ/heyoo#39]
With commit 41f7297 @nikbott added return types for getter methods this takes advantage of the newly introduces PEP 604: New Type Union Operator (https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator). This limits the library now to python 3.10 only. I think the projekt should support also older versions. This could be done using typing union (https://docs.python.org/3/library/typing.html#typing.Union).

**Comment by Kalebu** [comment]
Hi @soerenetler, Thanks for pointing that out 

I agree with you, older version should be supported, can you work on a pull request to fix this?

**Comment by filipporomani** [comment]
I just opened a pull for this. 
https://github.com/Neurotech-HQ/heyoo/pull/53 

I removed return type, I don't know if it's worth it or not.

**Comment by filipporomani** [comment]
@Kalebu this can be marked as closed now i suppose.

**Comment by Kalebu** [comment]
Sure , Closing it
