### ISSUE TITLE
How to send template with components

### ISSUE THREAD

**Issue by t0mer** [Neurotech-HQ/heyoo#41]
Hi,
Thanks for this amazing work.
Can you please share a code sample for sending a Template with parameters?

Thanks

**Comment by Kalebu** [comment]
Hi @t0mer 

I have included an example in the README.md 

>Here is a [link to an example](https://github.com/Neurotech-HQ/heyoo#sending-a-template-messages)

Please let me know if you're still having issues

**Comment by t0mer** [comment]
Thanks (:
