### ISSUE TITLE
Add functionality to send_sticker

### ISSUE THREAD

**Issue by soerenetler** [Neurotech-HQ/heyoo#43]
Hi,
currently the function to send stickers is not implemented. It should be possible to send stickers by id oder by file link.

**Comment by soerenetler** [comment]
maybe this could be combined with a generalized `send_media` function.
The functions `send_audio`, `send_video` and `send_image` are 90% code duplicates.

**Comment by Kalebu** [comment]
Hi @soerenetler 

I like the idea of having one method for `send_media`  for both  `send_audio`, `send_video` and `send_image`

Let's do this 

Also you can send a pull request for a method to support sending stickers and I will merge it right away 

Thank you 
Kalebu 

@soerenetler

**Comment by soerenetler** [comment]
I did take a look at the send sticker functionality. Do you have a file that is a valid sticker? I couldn't get it to actually send a sticker (everything works without error but I do not recieve anything). Or maybe also a valid sticker id?

**Comment by Kalebu** [comment]
You can try sending a sticker to WhatsApp Webhook and save the sticker_ID from the received data and use it for testing @soerenetler

**Comment by soerenetler** [comment]
I created a PR for stending sticker and custom json. #74
I Thought a little more about the send media function, but I am not sure, because they have very subtle differences. (like the caption).

**Comment by Kalebu** [comment]
Thank you @soerenetler I've already merged your pull request

You're the *heyoo* hero of the month

**Comment by Kalebu** [comment]
Can we now close this issue?

**Comment by soerenetler** [comment]
sure
