### ISSUE TITLE
get_file function not implemented

### ISSUE THREAD

**Issue by umerghayaz** [Neurotech-HQ/heyoo#45]
sir @Kalebu get_file function is not implemented.

**Comment by Kalebu** [comment]
Hello @umerghayaz 

Can you please tell me more about the issue ?

what does *get_file* supposed do or is it an error raised ?

Thank you
Kalebu

**Comment by umerghayaz** [comment]
you have implemented get_audio ,get_video function but you have not implemented get_file function in heyo library init file.

**Comment by umerghayaz** [comment]
elif message_type == "file":
                file = messenger.get_file(data)
                file_id, mime_type = file["id"], file["mime_type"]
                file_url = messenger.query_media_url(file_id)
                file_filename = messenger.download_media(file_url, mime_type)
                print(f"{mobile} sent file {file_filename}")
                logging.info(f"{mobile} sent file {file_filename}")
see the above example  in second line  " file = messenger.get_file(data) "  you have not implemented get_file function in heyoo library

**Comment by Kalebu** [comment]
Got it, must have have been forgotten 

Thanks for pointing that out 

You can submit the pull request with the implementation of it 

Let me know if you need any assistance from me to contribute 

Thank you
