### ISSUE TITLE
importing Heyoo is messing logging configuration

### ISSUE THREAD

**Issue by rbarcelos** [Neurotech-HQ/heyoo#56]
heyoo messes up logging init and it needs to be placed after basicConfig statement as fol;owing:

from flask_executor import Executor

LOG_FILE_NAME = "service.log"
logging.basicConfig(
    level=logging.DEBUG,
    filename=LOG_FILE_NAME,
    filemode="a+",
    format="%(asctime)-15s %(levelname)-8s %(message)s",
)

// Unfortunately heyoo messes up logging init, needs to be placed after basicConfig statement
from heyoo import \
    WhatsApp  # pylint: disable=wrong-import-position, wrong-import-order

**Comment by Kalebu** [comment]
Hey @rbarcelos  Can you please explain more about the issue with current logging and the your suggestion to fixing  it ?

**Comment by rbarcelos** [comment]
Disclaimer: I just started playing with Python so no guarantees that my guidance is correct..

Looking at your code (__iniit__.py), given the way that you are setting up logging, it will be done as soon as I import your module. For some reason, calling logging.basicConfig with my configs dont update it. 

One possible fix: make logging an optional parameter on WhatsApp ctor. So consumers can passe their instance instead of you creating yours. This is the famous dependency injection pattern

**Comment by soerenetler** [comment]
I tried to look into this a little and find some best practices. https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
I think the library should use `_logger = logging.getLogger(__name__)` and give the specific configuration to the user.
I could look into it further and create a PR.

**Comment by Kalebu** [comment]
I see
Please proceed @soerenetler

**Comment by Kalebu** [comment]
Resolved by #71
