### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by SamuelSilvaAraujo** [Neurotech-HQ/heyoo#58]

**Comment by SamuelSilvaAraujo** [comment]
bug in version 0.0.7

**Comment by Kalebu** [comment]
Hi @SamuelSilvaAraujo 

Can you please provide more description about the issue ?

**Comment by Kalebu** [comment]
Fixed, Please upgrade to heyoo latest version.
