### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by heraldjose10** [Neurotech-HQ/heyoo#64]
I believe there is a typo in the code snippet:

`intractive_type = message_response.get("type")`

Can we change it to interactive?

**Comment by Kalebu** [comment]
Yes sure @heraldjose10 

Can you send a pull request for this ?

**Comment by soerenetler** [comment]
I think this issue can be closed, right?

**Comment by heraldjose10** [comment]
Issue fixed #70
