### ISSUE TITLE
send template message in different translations (spanish)

### ISSUE THREAD

**Issue by adminsisifo** [Neurotech-HQ/heyoo#69]
Can the translation language be specified when using send template?

Template name does not exist in the translation
{'messaging_product': 'whatsapp', 'details': 'template name (hello_world_es) does not exist in en_US'}

**Comment by soerenetler** [comment]
Hi @adminsisifo,
the `send_template` and the `send_templatev2` accept `lang` as a keyword argument. Is this what you are searching for?

**Comment by filipporomani** [comment]
Updated docs in #76.

**Comment by Kalebu** [comment]
I will mark this issue as resolved
