### ISSUE TITLE
Sent Messages Undelivered

### ISSUE THREAD

**Issue by JAXPARROW** [Neurotech-HQ/heyoo#7]
![image](https://user-images.githubusercontent.com/16808182/169707204-866e6015-6b4b-4dfc-9b6a-b19ea3f5869c.png)

I have Flask webhook from the project folder running on port 5000 and I get 200 OK responses but I don't receive the messages, what am I missing here?

**Comment by Kalebu** [comment]
Your app network needs to be on the internet level, not localhost for it to be a valid callback URL 

So I recommend you to use  [Ngrok](https://ngrok.com/)  or any similar tool to map your local running host into some public URL which you can then go and paste to your Facebook developer portal
