### ISSUE TITLE
Only one method for sending templates

### ISSUE THREAD

**Issue by soerenetler** [Neurotech-HQ/heyoo#73]
Hi,
I think there should be only one method for sending templates. Currently there is no clear difference between `send_templatev2` and `send_template`. In my opinion `send_templatev2` sould be removed. If someone ist using it they shoud switch to `send_template`. Or did I miss anything here.

**Comment by Kalebu** [comment]
Correctly, There were some issues with the original implementation of `send_template` which they're now fixed and they all work exactly the same. 

How about introducing a depreciation warning first in the next version and then we can agree on the version to remove it completely?

**Comment by soerenetler** [comment]
ok, i will create a PR later.

**Comment by filipporomani** [comment]
Fixed in #76.

**Comment by Kalebu** [comment]
Resolved by #76
