### ISSUE TITLE
where can I get the token? (i have 3 different ones)

### ISSUE THREAD

**Issue by fylls** [Neurotech-HQ/heyoo#95]
Meta sucks, and here are some different tokens you can get:

### User Token & app token
you can get them both here: https://developers.facebook.com/tools/accesstoken/
![image](https://github.com/Neurotech-HQ/heyoo/assets/55017307/888799a8-5ca4-48d1-bd1b-567b95712309)

### system user token
this is generated inside meta's business settings
![image](https://hilos-media.s3.us-east-2.amazonaws.com/documentation/userdocs/getting-started/connect-a-new-number/generate-system-token.png)

which token is needed to use heyoo?

**Comment by Kalebu** [comment]
I will now close this
