### ISSUE TITLE
Function download_media: audio name format error

### ISSUE THREAD

**Issue by tinchoram** [Neurotech-HQ/heyoo#97]
👋 Hi, i have an issue when download media audio.

The audio name created is "temp.ogg; codecs=opus". it's cause an error to play file.

This happens because the whatsapp API response is example:

`[{'from': '54911XXXXXXXX', 'id': 'AA==', 'timestamp': '000000', 'type': 'audio', 'audio': {'mime_type': 'audio/ogg; codecs=opus', 'sha256': 'FAFAFA=', 'id': '000000', 'voice': True}}]`

the value `'mime_type': 'audio/ogg; codecs=opus'` is used for get extension of file in function: [download_media](https://github.com/Neurotech-HQ/heyoo/blob/main/heyoo/__init__.py#L720C9-L720C23)

in line: `extension = mime_type.split("/")[1]`

This caused that name will be `temp.ogg; codecs=opus` because the split catch all caracters after "/". 

---

To solve this problem, I modified the [line](https://github.com/Neurotech-HQ/heyoo/blob/45d78651ea943e3b009a82ba78cf34331c8892bf/heyoo/__init__.py#L743C9-L743C44) for :

`extension = mime_type.split("/")[1].split(";")[0].strip()`

it'a cause that name file will be format correctly and also works with other files extensions.

example: `"temp.ogg; codecs=opus"` formated to `temp.ogg` ✅

**Comment by Kalebu** [comment]
Merged, Thank you for taking your time to fix this
