### ISSUE TITLE
.send_message does not send messages

### ISSUE THREAD

**Issue by phantom153** [Neurotech-HQ/heyoo#99]
Hi,

Did everything right (I think), however - .send_message although outputs ok - does not send messages.
Here is my code:

```
token = 'EAAC14******'
messenger = WhatsApp(token,phone_number_id='12598*******')

messenger.send_message('Hello I am WhatsApp Cloud API', '972*******')
```

The output I get:

```
{'messaging_product': 'whatsapp',
 'contacts': [{'input': '972*******', 'wa_id': '972*******'}],
 'messages': [{'id': 'wamid.HBgMOTcyNTIzMjY4ODg4FQIAERgSQTk2RUFEQjVGQUU4NUI1OTgwAA=='}]}
```

However, the message is not received.

I am using Meta's test number. Using the code on Meta's site with the same token and number ID works.

**Any ideas?? Please HELP!**

**Comment by filipporomani** [comment]
Did you include the prefix in the phone number? 
Like if it's +39 the number should be "39xxxxx"

**Comment by phantom153** [comment]
@filipporomani  Thanks for the quick response. Yes I did

**Comment by filipporomani** [comment]
Try to also add `preview_url=False` in the send_message arguments

**Comment by filipporomani** [comment]
and also try to do this:
```python
token = 'EAAC14******'
messenger = WhatsApp(token,phone_number_id='12598*******')

msg = messenger.send_message('Hello I am WhatsApp Cloud API', '972*******')
print(msg) 
```

**Comment by phantom153** [comment]
> ```python
> msg = messenger.send_message('Hello I am WhatsApp Cloud API', '972*******')
> print(msg) 
> ```

Same result

**Comment by filipporomani** [comment]
so that you can see the full response output and get the error code. If you want to send the output it gives i may help you further.

**Comment by phantom153** [comment]
> ```python
> print(msg)
> ```

This is the output:

`{'messaging_product': 'whatsapp', 'contacts': [{'input': '972*****', 'wa_id': '972*****'}], 'messages': [{'id': 'wamid.HBgMOTcyNTIzMjY4ODg4FQIAERgSMjhDNkE4RTBCNTJDMjUwRDYwAA=='}]}`

**Comment by filipporomani** [comment]
same error for me. that's strange. lemme check with the api docs.

**Comment by phantom153** [comment]
> same error for me. that's strange. lemme check with the api docs.

That's good news for me :-)

**Comment by filipporomani** [comment]
have you got the payment method setted up on the facebook dev portal?

**Comment by phantom153** [comment]
Not yet. Is it a must while using only their test number?

**Comment by phantom153** [comment]
Please note that from the API setup page the "send message" button works well
![image](https://github.com/Neurotech-HQ/heyoo/assets/46167789/84ec6c61-dc2d-4ee1-bb62-665820ccdf76)

**Comment by filipporomani** [comment]
it's not then

**Comment by filipporomani** [comment]
try to send a message to the test number from your phone
and then try to send again via your code

**Comment by phantom153** [comment]
WOW!! That did the job!!! THANKS.

Can you explain why?

**Comment by filipporomani** [comment]
Facebook doesn't let you send custom messages to users if they don't start a conversation with you in the past 24 hours. If they don't start a conversation you can only send template messages to them (which is what you did with the send message button to test it).

**Comment by phantom153** [comment]
That is great. BUT does it mean that this will happen also on my regular usage of this service?
Is there a way to avoid the 24hours issue?

**Comment by filipporomani** [comment]
Sadly there is not. Btw you can edit the templates as you like, create new ones (you can also add variables to them) and send them directly.

**Comment by phantom153** [comment]
Ok. I will investigate this. Many thanks for your quick help!!

**Comment by filipporomani** [comment]
Happy to help! :-)
